#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "shatter"
$stdout.sync = true

require_relative "../config/environment"
require_relative "../application"

require 'irb'
IRB.start(__FILE__)
