name: Ruby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - github-actions

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test - Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.0'
          - '3.1.0'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: rspec
      run: bundle exec rspec
  lint:
    runs-on: ubuntu-latest
    name: Lint - Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.0'
          - '3.1.0'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: rubocop
      run: bundle exec rubocop
